const actions = {
    LOGIN: "LOGIN",
    CREATE_ORDER: "CREATE_ORDER",
    FETCH_RECEIVING_ORDERS: "FETCH_RECEIVING_ORDERS",
    FETCH_SENDED_ORDERS: "FETCH_SENDED_ORDERS",
    UPDATE_INFO: "UPDATE_INFO",
    REGISTER: "REGISTER",
    LOGOUT: "LOGOUT"
};

export default actions;